os: osx 

install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install acme
  - wget http://sdlmame.lngn.net/mame0214-64bit.zip
  - wget https://www.brutaldeluxe.fr/products/crossdevtools/cadius/Cadius_v1.4_mac.zip
  - unzip ./Cadius_v1.4_mac.zip
  - chmod +x ./cadius
  - unzip ./mame0214-64bit.zip
  - chmod +x ./mame0214-64bit/chdman
  - export PATH=$PATH:.:./mame0214-64bit

script:
  - make dsk chd

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: 
    - "build/4cade.2mg"
    - "build/4cade.2mg.chd"
  skip_cleanup: true
  draft: true