language: minimal

os: linux 

sudo: required

dist: xenial

addons:
  apt:
    sources:
      - debian-sid

install:

  - sudo apt-get install acme --allow-unauthenticated
  - wget -O ./cadius https://github.com/mach-kernel/cadius/releases/download/1.4.2/cadius-linux
  - chmod +x ./cadius
  - export PATH=$PATH:.

script:
  - make dsk

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "build/4cade.2mg"
  skip_cleanup: true
  draft: true