language: minimal

os: linux 

sudo: required

dist: xenial

addons:
  apt:
    sources:
      - debian-sid

install:

  - sudo apt-get install acme --allow-unauthenticated
  - wget https://github.com/mach-kernel/cadius/releases/download/1.4.2/cadius-linux
  - chmod +x cadius-linux
  - sudo ln -s ./cadius-linux /usr/local/bin/cadius

script:
  - make dsk