language: minimal

os: linux 

sudo: required

dist: xenial

addons:
  apt:
    sources:
      - debian-sid

install:
  - sudo apt-get install mame-tools --allow-unauthenticated
  - sudo apt-get install acme --allow-unauthenticated
  - wget -O ./cadius https://github.com/mach-kernel/cadius/releases/download/1.4.2/cadius-linux
  - chmod +x ./cadius
  - export PATH=$PATH:.

script:
  - make dsk chd

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: 
    - "build/4cade.2mg"
    - "build/4cade.chd"
  skip_cleanup: true
  draft: true