language: minimal

os: windows 

install:
  - wget https://netix.dl.sourceforge.net/project/acme-crossass/win32/acme0.96.4win.zip
  - wget https://www.brutaldeluxe.fr/products/crossdevtools/cadius/Cadius_v1.1.zip
  - 7z e acme0.96.4win.zip
  - 7z e Cadius_v1.1.zip
  - set PATH=%PATH%;.;.\acme0.96.4win\acme;

script:
  - winmake dsk

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: 
    - "build/4cade.2mg"
#    - "build/4cade.2mg.chd"
  skip_cleanup: true
  draft: true