os: osx 

install:
  - brew install acme
  - wget https://www.brutaldeluxe.fr/products/crossdevtools/cadius/Cadius_v1.1_mac.zip
  - unzip Cadius_v1.1_mac.zip
  - ln -s ./Cadius_v1.1_mac/Cadius_v1.1/Cadius ./cadius_v1.1_mac/Cadius_v1.1/cadius
  - chmod +x ./cadius_v1.1_mac/Cadius_v1.1/cadius
  - export PATH=$PATH:./Cadius_v1.1_mac/Cadius_v1.1;

script:
  - make dsk

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: 
    - "build/4cade.2mg"
#    - "build/4cade.2mg.chd"
  skip_cleanup: true
  draft: true