
Collect water drops but avoid cooling
off.  Green drops will make you hot and
ice cubes will try to cool you again.
Sitting on a volcano restores your
temperature.

         Keyboard or joystick

                   A
                 <- -> move
                   Z

J* * * * * * * * * * *activate joystick
K* * * * * * * * * *  activate keyboard 
P/B0 * * * * * * * * * * * * * * *pause
G/B1 * * * * * * * * * * * toggle sound
